### ISSUE TITLE
Plantage lorsqu'on contribue sur un magasin non référencé

### ISSUE THREAD

**Issue by Neimux** [HackCovid19CATS/vue-front#20]
Corriger le bug remonté par les utilisateurs ce matin concernant le plantage de l'appli quand on contribue sur un magasin non référencé.

Le nom du magasin est undefined, Lorsqu'on clic, sur contribuer, ce nom est utilisé pour former l'url.

**Comment by HackCovid19CATS** [comment]
A tester mais j'ai normalement corrigé ce point samedi dernier

**Comment by Neimux** [comment]
OK, j'ai testé,
"non référencé" est maintenant "nom de magasin inconnu" et nous pouvons bien contribuer dessus.
Je clôture
