### ISSUE TITLE
Page blanche ou grise sur certains smartphone

### ISSUE THREAD

**Issue by Neimux** [HackCovid19CATS/vue-front#22]
L'application ne se lance plus sur les smartphones Galaxy S8 et S9
page blanche lorsqu'on accède à l'application (navigateur Chrome)
L'application fonctionne si on coche "version pour ordinateur" mais c'est illisible

**Comment by HackCovid19CATS** [comment]
Quelle est la version de Chrome installée sur ces smartphones ?

**Comment by Neimux** [comment]
Pour ma part :
chrome : 80.0.3987.149 
OS: Android 9

**Comment by Neimux** [comment]
c’était peut être un pb de cache, je n'ai plus le pb en passant par https://dev.ca-cote.fr

**Comment by Neimux** [comment]
ça refonctionne également sur le Galaxy S9 de Karine
Donc je clôture
